import json
import os

os.makedirs('scenes/levels/maze', exist_ok=True)

with open('assets/temp/wall_boxes.json') as f:
    wall_boxes = json.load(f)

with open('assets/temp/torches.json') as f:
    torches = json.load(f)

lines = []
total_steps = 13 + len(wall_boxes)
lines.append(f'[gd_scene load_steps={total_steps} format=3]')
lines.append('')
lines.append('[ext_resource type="Script" path="res://scripts/world/maze_controller.gd" id="1_controller"]')
lines.append('[ext_resource type="Texture2D" path="res://assets/environment/maze/maze_map_clean.png" id="2_map_tex"]')
lines.append('[ext_resource type="PackedScene" path="res://scenes/player/player.tscn" id="3_player"]')
lines.append('[ext_resource type="PackedScene" path="res://scenes/world/camera_rig.tscn" id="4_camera"]')
lines.append('[ext_resource type="Texture2D" path="res://assets/environment/maze/key_gold.png" id="5_key_tex"]')
lines.append('[ext_resource type="Texture2D" path="res://assets/environment/maze/chest_gold.png" id="6_chest_tex"]')
lines.append('[ext_resource type="Texture2D" path="res://assets/environment/maze/gate_iron_large.png" id="7_gate_tex"]')
lines.append('[ext_resource type="PackedScene" path="res://scenes/world/black_tunnel.tscn" id="8_tunnel_scene"]')
lines.append('')
lines.append('[sub_resource type="Environment" id="Environment_maze"]')
lines.append('background_mode = 1')
lines.append('background_color = Color(0.02, 0.015, 0.03, 1)')
lines.append('ambient_light_source = 2')
lines.append('ambient_light_color = Color(0.28, 0.20, 0.26, 1)')
lines.append('ambient_light_energy = 0.65')
lines.append('tonemap_mode = 2')
lines.append('')
lines.append('[sub_resource type="BoxShape3D" id="Shape_Floor"]')
lines.append('size = Vector3(24, 1, 16)')
lines.append('')
lines.append('[sub_resource type="BoxShape3D" id="Shape_KeyTrigger"]')
lines.append('size = Vector3(1.2, 1.5, 1.2)')
lines.append('')
lines.append('[sub_resource type="BoxShape3D" id="Shape_ChestTrigger"]')
lines.append('size = Vector3(1.4, 1.5, 1.4)')
lines.append('')
lines.append('[sub_resource type="BoxShape3D" id="Shape_ExitTrigger"]')
lines.append('size = Vector3(2.2, 2.0, 2.0)')
lines.append('')

# Generate sub-resources for wall collision shapes
for i, box in enumerate(wall_boxes):
    lines.append(f'[sub_resource type="BoxShape3D" id="Shape_Wall_{i}"]')
    lines.append(f'size = Vector3({box["sx"]}, 2.5, {box["sz"]})')
    lines.append('')

# Root node
lines.append('[node name="Maze" type="Node3D"]')
lines.append('script = ExtResource("1_controller")')
lines.append('')
lines.append('[node name="WorldEnvironment" type="WorldEnvironment" parent="."]')
lines.append('environment = SubResource("Environment_maze")')
lines.append('')
lines.append('[node name="DirectionalLight3D" type="DirectionalLight3D" parent="."]')
lines.append('transform = Transform3D(0.866025, -0.25, 0.433013, 0, 0.866025, 0.5, -0.5, -0.433013, 0.75, 0, 15, 0)')
lines.append('light_color = Color(0.7, 0.65, 0.8, 1)')
lines.append('light_energy = 0.35')
lines.append('shadow_enabled = false')
lines.append('')

# Map visual
lines.append('[node name="DungeonVisual" type="Sprite3D" parent="."]')
lines.append('transform = Transform3D(1, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0.01, 0)')
lines.append('pixel_size = 0.0125')
lines.append('texture_filter = 0')
lines.append('sorting_offset = -10.0')
lines.append('texture = ExtResource("2_map_tex")')
lines.append('')

# Floor ground
lines.append('[node name="FloorGround" type="StaticBody3D" parent="."]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -0.5, 0)')
lines.append('')
lines.append('[node name="CollisionShape3D" type="CollisionShape3D" parent="FloorGround"]')
lines.append('shape = SubResource("Shape_Floor")')
lines.append('')

# Wall Collisions
lines.append('[node name="MazeWalls" type="Node3D" parent="."]')
lines.append('')
for i, box in enumerate(wall_boxes):
    lines.append(f'[node name="{box["name"]}" type="StaticBody3D" parent="MazeWalls"]')
    lines.append(f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {box["x"]}, 1.25, {box["z"]})')
    lines.append('')
    lines.append(f'[node name="CollisionShape3D" type="CollisionShape3D" parent="MazeWalls/{box["name"]}"]')
    lines.append(f'shape = SubResource("Shape_Wall_{i}")')
    lines.append('')

# Torches
lines.append('[node name="MazeDecorations" type="Node3D" parent="."]')
lines.append('')
lines.append('[node name="Torches" type="Node3D" parent="MazeDecorations"]')
lines.append('')
for t in torches:
    lines.append(f'[node name="TorchLight_{t["id"]}" type="OmniLight3D" parent="MazeDecorations/Torches"]')
    lines.append(f'transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, {t["x"]}, 0.5, {t["z"]})')
    lines.append('light_color = Color(1, 0.65, 0.28, 1)')
    lines.append('light_energy = 1.6')
    lines.append('omni_range = 3.2')
    lines.append('omni_attenuation = 1.2')
    lines.append('')

# Interactables
lines.append('[node name="Interactables" type="Node3D" parent="."]')
lines.append('')

# Golden Key: x=1.75, z=-3.42
lines.append('[node name="GoldenKey" type="Area3D" parent="Interactables"]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 1.75, 0.2, -3.42)')
lines.append('')
lines.append('[node name="CollisionShape3D" type="CollisionShape3D" parent="Interactables/GoldenKey"]')
lines.append('shape = SubResource("Shape_KeyTrigger")')
lines.append('')
lines.append('[node name="KeyVisual" type="Sprite3D" parent="Interactables/GoldenKey"]')
lines.append('transform = Transform3D(1, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0.25, 0)')
lines.append('pixel_size = 0.0125')
lines.append('texture_filter = 0')
lines.append('texture = ExtResource("5_key_tex")')
lines.append('')
lines.append('[node name="KeyLight" type="OmniLight3D" parent="Interactables/GoldenKey"]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0.3, 0)')
lines.append('light_color = Color(1, 0.85, 0.3, 1)')
lines.append('light_energy = 1.2')
lines.append('omni_range = 1.8')
lines.append('')

# Chest: x=6.15, z=2.47
lines.append('[node name="Chest" type="Area3D" parent="Interactables"]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 6.15, 0.2, 2.47)')
lines.append('')
lines.append('[node name="CollisionShape3D" type="CollisionShape3D" parent="Interactables/Chest"]')
lines.append('shape = SubResource("Shape_ChestTrigger")')
lines.append('')
lines.append('[node name="ChestVisual" type="Sprite3D" parent="Interactables/Chest"]')
lines.append('transform = Transform3D(1, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0.15, 0)')
lines.append('pixel_size = 0.0125')
lines.append('texture_filter = 0')
lines.append('texture = ExtResource("6_chest_tex")')
lines.append('')

# Exit Gate: x=7.27, z=-4.65
lines.append('[node name="MazeExit" type="Area3D" parent="Interactables"]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 7.27, 0.2, -4.65)')
lines.append('')
lines.append('[node name="CollisionShape3D" type="CollisionShape3D" parent="Interactables/MazeExit"]')
lines.append('shape = SubResource("Shape_ExitTrigger")')
lines.append('')
lines.append('[node name="GateVisual" type="Sprite3D" parent="Interactables/MazeExit"]')
lines.append('transform = Transform3D(1, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0.15, 0)')
lines.append('pixel_size = 0.0125')
lines.append('texture_filter = 0')
lines.append('texture = ExtResource("7_gate_tex")')
lines.append('')
lines.append('[node name="Prompt" type="Label3D" parent="Interactables/MazeExit"]')
lines.append('transform = Transform3D(1, 0, 0, 0, 0, 1, 0, -1, 0, 0, 0.6, 0.5)')
lines.append('billboard = 1')
lines.append('text = "[E] Unlock Exit Gate"')
lines.append('font_size = 24')
lines.append('')
lines.append('[node name="MouseTunnels" type="Node3D" parent="."]')
lines.append('')
lines.append('[node name="BlackTunnel_A" parent="MouseTunnels" instance=ExtResource("8_tunnel_scene")]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -8.16, 0.05, 2.0)')
lines.append('tunnel_id = "BlackTunnel_A"')
lines.append('destination_id = "BlackTunnel_B"')
lines.append('emergence_offset = Vector3(0, 0, 0.4)')
lines.append('')
lines.append('[node name="BlackTunnel_B" parent="MouseTunnels" instance=ExtResource("8_tunnel_scene")]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 4.5, 0.05, 2.0)')
lines.append('tunnel_id = "BlackTunnel_B"')
lines.append('destination_id = "BlackTunnel_A"')
lines.append('emergence_offset = Vector3(0, 0, 0.4)')
lines.append('')

# PlayerSpawn: x=-8.16, z=4.9
lines.append('[node name="PlayerSpawn" type="Marker3D" parent="."]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -8.16, 0.1, 4.9)')
lines.append('')

# Player instance
lines.append('[node name="Player" parent="." groups=["player"] instance=ExtResource("3_player")]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -8.16, 0.1, 4.9)')
lines.append('')

# CameraRig instance
lines.append('[node name="CameraRig" parent="." instance=ExtResource("4_camera")]')
lines.append('transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -8.16, 0.1, 4.9)')
lines.append('')

# MazeHUD (CanvasLayer)
lines.append('[node name="MazeHUD" type="CanvasLayer" parent="."]')
lines.append('')
lines.append('[node name="Margin" type="MarginContainer" parent="MazeHUD"]')
lines.append('anchors_preset = 15')
lines.append('anchor_right = 1.0')
lines.append('anchor_bottom = 1.0')
lines.append('grow_horizontal = 2')
lines.append('grow_vertical = 2')
lines.append('theme_override_constants/margin_left = 20')
lines.append('theme_override_constants/margin_top = 16')
lines.append('theme_override_constants/margin_right = 20')
lines.append('theme_override_constants/margin_bottom = 16')
lines.append('')
lines.append('[node name="VBox" type="VBoxContainer" parent="MazeHUD/Margin"]')
lines.append('layout_mode = 2')
lines.append('size_flags_vertical = 0')
lines.append('')
lines.append('[node name="TopBar" type="HBoxContainer" parent="MazeHUD/Margin/VBox"]')
lines.append('layout_mode = 2')
lines.append('')
lines.append('[node name="FormBadge" type="Label" parent="MazeHUD/Margin/VBox/TopBar"]')
lines.append('layout_mode = 2')
lines.append('theme_override_colors/font_color = Color(1, 0.85, 0.3, 1)')
lines.append('theme_override_font_sizes/font_size = 18')
lines.append('text = "FORM: MUSHIKA"')
lines.append('')
lines.append('[node name="Spacer1" type="Control" parent="MazeHUD/Margin/VBox/TopBar"]')
lines.append('layout_mode = 2')
lines.append('size_flags_horizontal = 3')
lines.append('')
lines.append('[node name="ObjectiveLabel" type="Label" parent="MazeHUD/Margin/VBox/TopBar"]')
lines.append('layout_mode = 2')
lines.append('theme_override_colors/font_color = Color(0.9, 0.85, 0.95, 1)')
lines.append('theme_override_font_sizes/font_size = 16')
lines.append('text = "Objective: Search the maze for the Golden Key"')
lines.append('')
lines.append('[node name="Spacer2" type="Control" parent="MazeHUD/Margin/VBox/TopBar"]')
lines.append('layout_mode = 2')
lines.append('size_flags_horizontal = 3')
lines.append('')
lines.append('[node name="KeyTracker" type="Label" parent="MazeHUD/Margin/VBox/TopBar"]')
lines.append('layout_mode = 2')
lines.append('theme_override_colors/font_color = Color(1, 0.8, 0.2, 1)')
lines.append('theme_override_font_sizes/font_size = 18')
lines.append('text = "Keys: 0 / 1"')
lines.append('')
lines.append('[node name="MessageBanner" type="Label" parent="MazeHUD/Margin"]')
lines.append('layout_mode = 2')
lines.append('size_flags_horizontal = 4')
lines.append('size_flags_vertical = 8')
lines.append('theme_override_colors/font_color = Color(1, 0.95, 0.85, 1)')
lines.append('theme_override_font_sizes/font_size = 20')
lines.append('horizontal_alignment = 1')
lines.append('vertical_alignment = 1')
lines.append('')

with open('scenes/levels/maze/maze.tscn', 'w') as f:
    f.write('\n'.join(lines))

print('scenes/levels/maze/maze.tscn generated successfully!')
